export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';

export const SEARCH_BOOK_TITLE = 'SEARCH_BOOK_TITLE';
export const LOAD_SEARCH_BOOKS_SUCCESS = 'LOAD_SEARCH_BOOKS_SUCCESS';

export const UPDATE_BAR_RSVP = 'UPDATE_BAR_RSVP';
export const UPDATE_ALL_RSVPS = 'UPDATE_ALL_RSVPS';