const books = [ 
  { title: 'Dr. Dobb\'s Toolbook of 80286/80386 Programming',
    authors: [ 'Phillip R. Robinson' ],
    publisher: 'Prentice Hall',
    publishedDate: '1988-01-01',
    industryIdentifiers: [ [Object] ],
    pageCount: 731,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'mjgiAQAAIAAJ',
    link: 'https://books.google.com/books/about/Dr_Dobb_s_Toolbook_of_80286_80386_Progra.html?hl=&id=mjgiAQAAIAAJ',
    thumbnail: 'http://books.google.com/books/content?id=mjgiAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} },
  { title: 'Virtual Migration: The Programming of Globalization',
    authors: [ 'Aneesh' ],
    publisher: 'Pearson Education India',
    industryIdentifiers: [ [Object], [Object] ],
    printType: 'BOOK',
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'soe1mQUjD_0C',
    link: 'https://books.google.com/books/about/Virtual_Migration_The_Programming_of_Glo.html?hl=&id=soe1mQUjD_0C',
    thumbnail: 'http://books.google.com/books/content?id=soe1mQUjD_0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Logic programming for parallel implementation',
    authors: [ 'Allen Van Gelder' ],
    publishedDate: '1986',
    industryIdentifiers: [ [Object] ],
    pageCount: 200,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'EfJEAQAAIAAJ',
    link: 'https://books.google.com/books/about/Logic_programming_for_parallel_implement.html?hl=&id=EfJEAQAAIAAJ',
    thumbnail: 'http://books.google.com/books/content?id=EfJEAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} },
  { title: 'Advanced 6502 Programming',
    authors: [ 'Rodnay Zaks' ],
    publishedDate: '1982-01-01',
    description: 'Teaches Advanced Techniques Ranging from Algorithms and Data Structure Design to Code Optimization and Register Allocation',
    industryIdentifiers: [ [Object] ],
    pageCount: 292,
    printType: 'BOOK',
    categories: [ '6502 (Microprocessor)' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: '7YngAAAAMAAJ',
    link: 'https://books.google.com/books/about/Advanced_6502_Programming.html?hl=&id=7YngAAAAMAAJ',
    thumbnail: 'http://books.google.com/books/content?id=7YngAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} },
  { title: 'Objective-C Programming',
    subtitle: 'The Big Nerd Ranch Guide',
    authors: [ 'Aaron Hillegass' ],
    publisher: 'Pearson Education',
    publishedDate: '2011-11-22',
    description: 'Want to write applications for iOS or the Mac? This introduction to programming and the Objective-C language is the first step on your journey from someone who uses apps to someone who writes them. Based on Big Nerd Ranch\'s legendary Objective-C Bootcamp,¿this book covers C, Objective-C, and the common programming idioms that enable developers to make the most of Apple technologies. This is the only introductory-level book written by Aaron Hillegass, one of the most experienced and authoritative voices in the iOS and Cocoa community. Compatible with Xcode 4.2, iOS 5, and Mac OS X 10.7 (Lion), this guide features short chapters and engaging style to keep you motivated and moving forward. At the same time, Aaron’s determination that you understand what you’re doing—or at least why you’re doing it—encourages you to think critically as a programmer.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 288,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: '-36tpV118R4C',
    link: 'https://books.google.com/books/about/Objective_C_Programming.html?hl=&id=-36tpV118R4C',
    thumbnail: 'http://books.google.com/books/content?id=-36tpV118R4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The OpenCL Programming Book',
    authors: [ 'http://www.fixstars.com/en/opencl/book/' ],
    publisher: 'Fixstars',
    printType: 'BOOK',
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'O86m1hJxA6QC',
    link: 'https://books.google.com/books/about/The_OpenCL_Programming_Book.html?hl=&id=O86m1hJxA6QC',
    thumbnail: 'http://books.google.com/books/content?id=O86m1hJxA6QC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Dynamic Programming and Stochastic Control',
    authors: [ 'Bertsekas' ],
    publisher: 'Academic Press',
    publishedDate: '1976-11-26',
    description: 'Dynamic Programming and Stochastic Control',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 396,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 5,
    ratingsCount: 1,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'OnxEmDRM7OEC',
    link: 'https://market.android.com/details?id=book-OnxEmDRM7OEC',
    thumbnail: 'http://books.google.com/books/content?id=OnxEmDRM7OEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Lance Leventhal\'s 80386 Programming Guide',
    authors: [ 'Lance A. Leventhal' ],
    publisher: 'Bantam Dell Publishing Group',
    publishedDate: '1987',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 351,
    printType: 'BOOK',
    categories: [ 'Electronic digital computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'YYPZAAAAMAAJ',
    link: 'https://books.google.com/books/about/Lance_Leventhal_s_80386_Programming_Guid.html?hl=&id=YYPZAAAAMAAJ',
    thumbnail: 'http://books.google.com/books/content?id=YYPZAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} },
  { title: 'Plaid for Linear Programming',
    authors: [ 'Wainwright E. Martin', 'E Wainright Martin' ],
    publisher: 'Dorsey Press',
    publishedDate: '1974-01-01',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 187,
    printType: 'BOOK',
    categories: [ 'Mathematics' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'M2hlAaN_0HAC',
    link: 'https://books.google.com/books/about/Plaid_for_Linear_Programming.html?hl=&id=M2hlAaN_0HAC',
    thumbnail: 'http://books.google.com/books/content?id=M2hlAaN_0HAC&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} },
  { title: 'Linear programming and applications',
    subtitle: 'a course text',
    authors: [ 'Will McLewin' ],
    publishedDate: '1982',
    industryIdentifiers: [ [Object] ],
    pageCount: 216,
    printType: 'BOOK',
    categories: [ 'Mathematics' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'WDkoAQAAMAAJ',
    link: 'https://books.google.com/books/about/Linear_programming_and_applications.html?hl=&id=WDkoAQAAMAAJ',
    thumbnail: 'http://books.google.com/books/content?id=WDkoAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} }
] ;

module.exports = {
	books
}
